#!/usr/bin/env bash
# mirror-local.sh — mirror all images in mirrors.yaml to GHCR from your local machine.
#
# Usage:
#   ./scripts/mirror-local.sh [name_filter]
#
# Examples:
#   ./scripts/mirror-local.sh            # mirror everything
#   ./scripts/mirror-local.sh postgres   # mirror only entries whose name contains "postgres"
#
# Prerequisites:
#   skopeo, yq, jq  (all present on this machine)
#   GHCR login:  skopeo login ghcr.io -u Ic3W0rld --password-stdin  <<< "$GITHUB_TOKEN"

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
MIRRORS_FILE="${REPO_DIR}/mirrors.yaml"
LOCK_FILE="${REPO_DIR}/mirrors.lock.yaml"

GHCR="ghcr.io"
OWNER="ic3w0rld"
ARCH="amd64"
OS="linux"
NAME_FILTER="${1:-}"

# --------------------------------------------------------------------------- #
# Auth — always (re)login when GITHUB_TOKEN is present; fail fast otherwise
# Required PAT scopes: write:packages  (classic PAT)
#                   OR Packages: Read & Write  (fine-grained PAT)
# --------------------------------------------------------------------------- #
if [[ -z "${GITHUB_TOKEN:-}" ]]; then
  echo "ERROR: GITHUB_TOKEN is not set."
  echo ""
  echo "Create a classic PAT at https://github.com/settings/tokens with scope:"
  echo "  write:packages"
  echo ""
  echo "Then run:"
  echo "  export GITHUB_TOKEN=<your-PAT>"
  echo "  ./scripts/mirror-local.sh"
  exit 1
fi

echo "Logging in to GHCR..."
echo "$GITHUB_TOKEN" | skopeo login "$GHCR" -u "$OWNER" --password-stdin

# --------------------------------------------------------------------------- #
# Mirror loop
# --------------------------------------------------------------------------- #
TMP_LOCK=$(mktemp)

{
  echo "# AUTO-GENERATED by mirror-local.sh - do not edit by hand."
  echo "# Run ./scripts/mirror-local.sh to refresh."
  echo "images:"
} > "$TMP_LOCK"

count=0
errors=0
total=$(yq '.images | length' "$MIRRORS_FILE")

echo "Starting mirror run: $total images, arch=${ARCH}"
echo ""

for (( i=0; i<total; i++ )); do
  name=$(yq ".images[$i].name" "$MIRRORS_FILE")
  source=$(yq ".images[$i].source" "$MIRRORS_FILE")
  tag=$(yq ".images[$i].tag" "$MIRRORS_FILE")
  resolve=$(yq ".images[$i].resolve_latest // \"false\"" "$MIRRORS_FILE")

  if [[ -n "$NAME_FILTER" && "$name" != *"$NAME_FILTER"* ]]; then
    continue
  fi

  src="docker://${source}:${tag}"
  dst_base="${GHCR}/${OWNER}/${name}"
  resolved_tag="$tag"

  printf "[%2d/%d] %-40s  %s:%s\n" "$((i+1))" "$total" "$name" "$source" "$tag"

  # Resolve latest -> semver via OCI version label
  if [[ "$resolve" == "true" ]]; then
    version=$(skopeo inspect \
      --override-arch "$ARCH" \
      --override-os   "$OS" \
      "$src" 2>/dev/null \
      | jq -r '.Labels["org.opencontainers.image.version"] // empty' || true)

    if [[ -n "$version" && "$version" != "$tag" ]]; then
      echo "         resolved: $tag -> $version"
      resolved_tag="$version"
    else
      echo "         no version label found, keeping tag: $tag"
    fi
  fi

  # Copy with original tag
  if skopeo copy \
      --override-arch "$ARCH" \
      --override-os   "$OS" \
      "$src" \
      "docker://${dst_base}:${tag}" 2>&1 | tail -1; then
    count=$((count + 1))
  else
    echo "  ERROR: failed to copy ${source}:${tag}"
    errors=$((errors + 1))
    {
      echo "  - name: ${name}"
      echo "    source: ${source}"
      echo "    upstream_tag: ${tag}"
      echo "    ghcr: ${dst_base}"
      echo "    resolved_tag: ERROR"
    } >> "$TMP_LOCK"
    continue
  fi

  # Also copy with resolved semver tag if different
  if [[ "$resolved_tag" != "$tag" ]]; then
    skopeo copy \
      --override-arch "$ARCH" \
      --override-os   "$OS" \
      "$src" \
      "docker://${dst_base}:${resolved_tag}" 2>&1 | tail -1 || true
  fi

  {
    echo "  - name: ${name}"
    echo "    source: ${source}"
    echo "    upstream_tag: ${tag}"
    echo "    ghcr: ${dst_base}"
    echo "    resolved_tag: ${resolved_tag}"
  } >> "$TMP_LOCK"

  echo ""
done

mv "$TMP_LOCK" "$LOCK_FILE"

# --------------------------------------------------------------------------- #
# Commit lock file
# --------------------------------------------------------------------------- #
cd "$REPO_DIR"
git add mirrors.lock.yaml
if git diff --cached --quiet; then
  echo "mirrors.lock.yaml unchanged."
else
  git commit -m "chore: update mirrors.lock.yaml"
  git push origin main
  echo "mirrors.lock.yaml committed and pushed."
fi

echo ""
echo "Done. Mirrored: ${count}  Errors: ${errors}"
if [[ $errors -gt 0 ]]; then
  echo "Check the output above for failed images."
  exit 1
fi
